webserver:
  port: 3020
  host: "0.0.0.0"
  name: "example"
  alpnVersions:
    - "HTTP_2"
    - "HTTP_1_1"
  prefix: "/api/*"
  timeout: 30000
  logEnabled: true
  ignorePaths:
    - "/api/example/health"

database:
  mysql:
    host: "192.168.2.234"
    port: 3306
    username: "integrated_dev"
    password: "anjun123"
    database: "integrated_dev"
    # 时间配置单位s
    maxPoolSize: 16
    idleTimeout: 30
    connectionTimeout: 2
    maxLifetime: 1800
    maxWaitQueueSize: 5000

vertx:
  verticle: com.vertx.example.verticle.MainVerticle
  instances: 1
  ha: true

webclient:
  maxPoolSize: 16
  connectTimeout: 2000
  readIdleTimeout: 20000
  idleTimeout: 10000
  writeIdleTimeout: 10000
