webServer: # web服务配置
  port: 3020 # 服务端口
  host: "0.0.0.0" # 服务绑定的ip
  name: "example" # 服务名称
  alpnVersions: # 支持的协议版本
    - "HTTP_2"
    - "HTTP_1_1"
  prefix: "/api/*" # 路由前缀
  timeout: 30000 # web请求超时时间
  logEnabled: true # 是否开启日志
  ignorePaths: # 忽略的路径
    - "/api/example/health"

database: # 数据库配置
  mysql: # mysql数据库配置
    host: "192.168.2.234" # 数据库地址
    port: 3306 # 数据库端口
    username: "integrated_dev" # 数据库用户名
    password: "anjun123" # 数据库密码
    database: "integrated_dev" # 数据库名称
    charset: "utf8mb4" # 数据库编码
    timezone: "Asia/Shanghai" # 数据库时区
    maxPoolSize: 16 # 最大连接数 时间配置单位s
    idleTimeout: 30 # 空闲连接超时时间
    connectionTimeout: 2 # 连接超时时间
    maxLifetime: 1800 # 连接最大生命周期
    maxWaitQueueSize: 5000 # 最大等待队列数

vertx: # vertx配置
  verticle: com.vertx.example.verticle.MainVerticle # verticle类
  instances: 1 # verticle实例数
  ha: true # 是否开启ha

webClient: # web客户端配置
  maxPoolSize: 16 # 最大连接数
  connectTimeout: 2000 # 连接超时时间
  readIdleTimeout: 20000 # 读取超时时间
  idleTimeout: 10000 # 空闲连接超时时间
  writeIdleTimeout: 10000 # 写入超时时间
