server:
  port: 3020
database:
  mysql:
    url: ""
    username: ""
    password: ""
    database: ""
  redis:
    url: ""
    database: 0
    password: ""

vertx:
  verticle: com.vertx.example.verticle.MainVerticle
  instances: 1
  ha: true

webclient:
  maxPoolSize: 16
  connectTimeout: 2000
  readIdleTimeout: 20000
  idleTimeout: 10000
  writeIdleTimeout: 10000
