app: # 应用配置
  name: "example" # 应用名称
  version: "1.0.0" # 应用版本
  description: "示例项目" # 应用描述

database: # 数据库配置
  mysql: # mysql数据库配置
    host: "127.0.0.1" # 数据库地址
    port: 3306 # 数据库端口
    username: "root" # 数据库用户名
    password: "123456" # 数据库密码
    database: "vertx-example" # 数据库名称
    charset: "utf8mb4" # 数据库编码
    timezone: "Asia/Shanghai" # 数据库时区
    maxPoolSize: 16 # 最大连接数 时间配置单位s
    idleTimeout: 30 # 空闲连接超时时间
    connectionTimeout: 2 # 连接超时时间
    maxLifetime: 1800 # 连接最大生命周期
    maxWaitQueueSize: 5000 #

vertx: # vertx配置
  verticle: com.vertx.example.verticle.MainVerticle # verticle类
  instances: 1 # verticle实例数
  ha: true # 是否开启ha

